FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata

ARG TARGETARCH
ARG TARGETVARIANT=""

COPY linux/${TARGETARCH}/${TARGETVARIANT}/unlock-monitor /usr/local/bin/unlock-monitor

CMD ["unlock-monitor"]
