FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata

ARG TARGETARCH
ARG TARGETVARIANT=""

COPY bin-linux-${TARGETARCH}${TARGETVARIANT} /usr/local/bin/unlock-monitor

CMD ["unlock-monitor"]
